location = "local-1"
server_id = 1
num_clients = 2 # Hardcoded number of direct client connections to wait for
listen_address = "127.0.0.1"
listen_port = 8001
proxy_address = "127.0.0.1:9000"
use_proxy = true
adaptive_deadline = false
default_deadline = 1000
failure_injection = false
failure_probability = 0.0
failure_check_interval_ms = 1000
failure_downtime_ms = 0
failure_max_events = 0
output_filepath = "./logs/server-1.json"

[clock]
drift_rate = 0
uncertainty_bound = 100
sync_freq = 100
