location = "local-3"
server_id = 3
num_clients = 1 # Hardcoded number of client connections to wait for
listen_address = "127.0.0.1"
listen_port = 8003
proxy_address = "127.0.0.1:9000"
use_proxy = true
output_filepath = "./logs/server-3.json"

[clock]
drift_rate = 0
uncertainty_bound = 100
sync_freq = 100
