location = "local-2"
server_id = 2
num_clients = 0 # No direct clients; traffic only via proxy
listen_address = "127.0.0.1"
listen_port = 8002
proxy_address = "127.0.0.1:9000"
use_proxy = true
adaptive_deadline = false
default_deadline = 1000
output_filepath = "./logs/server-2.json"

[clock]
drift_rate = 0
uncertainty_bound = 1000
sync_freq = 10
