location = "local-1"
server_id = 1 # the server to connect
server_address = "127.0.0.1:8001"
proxy_address = "127.0.0.1:9000"
use_proxy = true
summary_filepath = "./logs/client-1.json"
output_filepath = "./logs/client-1.csv"

# Defining TOML vector of (duration_sec, requests_per_sec, read_ratio) which determines the behavior of the client requests
[[requests]]
duration_sec = 20
requests_per_sec = 10
read_ratio = 0.25
