location = "raw-2"
server_id = 2
num_clients = 0
listen_address = "127.0.0.1"
listen_port = 8002
proxy_address = "127.0.0.1:9000"
use_proxy = false
adaptive_deadline = false
default_deadline = 1000
failure_injection = false
failure_probability = 0.0
failure_check_interval_ms = 1000
failure_downtime_ms = 0
failure_max_events = 0
output_filepath = "./logs/server-2.json"

[clock]
drift_rate = 0
uncertainty_bound = 10
sync_freq = 1
